name: humane
description: An open source humanitarian application.

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
   # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  scoped_model: ^1.1.0

  #BLoC Arquitecture
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  validators: ^3.0.0
  flutter_svg: ^1.0.3
  webview_flutter: ^0.3.19+9
  circular_bottom_navigation: ^2.0.0
  introduction_screen: ^3.0.0
  angles: ^2.1.1
  flutter_hooks: ^0.18.2+1
  rxdart: ^0.27.3
  http_interceptor: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.9
  equatable: ^2.0.3
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.9.2
  flutter_dotenv: ^5.0.2
  graphql_flutter: ^5.0.1
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: LEMONMILK-bold
      fonts:
        - asset: assets/fonts/lemon/LEMONMILK-Bold.otf
    - family: LEMONMILK-light
      fonts:
        - asset: assets/fonts/lemon/LEMONMILK-Light.otf
    - family: LEMONMILK-regular
      fonts:
        - asset: assets/fonts/lemon/LEMONMILK-Regular.otf
    - family: Montserrat-bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
    - family: Montserrat-light
      fonts:
        - asset: assets/fonts//montserrat/Montserrat-Light.otf
    - family: Montserrat-regular
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
    - family: Montserrat-medium
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
    - family: Humane
      fonts:
        - asset: assets/icons/Humane.ttf

  # uses-material-design: true


  assets:
    - .env.dev
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/signin.svg
    - assets/icons/storage.svg
    - assets/icons/detailTop.svg
    - assets/icons/detailTopOpacity.svg
    - assets/icons/detailBottom.svg
    - assets/icons/promobg.svg
    - assets/icons/intro1.svg
    - assets/icons/intro2.svg
    - assets/icons/intro3.svg

