name: humane
description: An open source humanitarian application.

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  webview_flutter: ^0.3.19+9
  rxdart: ^0.27.3

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  scoped_model: ^1.1.0

  #BLoC Arquitecture
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  #Flare 
  flare_flutter: ^3.0.2

  #SVG
  flutter_svg: ^1.0.3

  #Validation
  validators: ^3.0.0

  #Equatable
  equatable: ^2.0.3

  #Hooks
  flutter_hooks: ^0.18.2+1

  #.env
  flutter_dotenv: ^5.0.2
  
  #graphql
  graphql_flutter: ^5.0.1
  
  http_interceptor: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.9
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Humane
      fonts:
        - asset: assets/icons/Humane.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 800
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 200
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
      

  # uses-material-design: true

  assets:
    - .env.dev
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/signin.svg
    - assets/icons/storage.svg
    - assets/icons/detailTop.svg
    - assets/icons/detailTopOpacity.svg
    - assets/icons/detailBottom.svg
    - assets/icons/promobg.svg
    - assets/icons/intro1.svg
    - assets/icons/intro2.svg
    - assets/icons/intro3.svg
    - lib/core/flavors/env/
    - assets/icons/
    - assets/images/
    - assets/animations/


