name: humane
description: An open source humanitarian application.

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  flare_splash_screen: ^3.0.1
  font_awesome_flutter: ^8.7.0
  flutter_svg: ^1.0.3
  flutter_recaptcha_v2: ^0.1.0
  webview_flutter: ^0.3.19+9
  circular_bottom_navigation: ^1.0.1
  introduction_screen: ^1.0.8
  angles: ^1.2.1
  get_it: ^4.0.2
  scoped_model: ^1.0.1
  flutter_hooks: ^0.18.2+1
  moor: ^3.2.0
  rxdart: ^0.24.1
  http_interceptor: ^0.3.2
  path:
  path_provider:
  equatable: ^1.2.2
  dartz: ^0.8.6
  bloc: ^8.0.3
  flutter_launcher_icons: ^0.9.2

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: LEMONMILK-bold
      fonts:
        - asset: assets/fonts/lemon/LEMONMILK-Bold.otf
    - family: LEMONMILK-light
      fonts:
        - asset: assets/fonts/lemon/LEMONMILK-Light.otf
    - family: LEMONMILK-regular
      fonts:
        - asset: assets/fonts/lemon/LEMONMILK-Regular.otf
    - family: Montserrat-bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
    - family: Montserrat-light
      fonts:
        - asset: assets/fonts//montserrat/Montserrat-Light.otf
    - family: Montserrat-regular
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
    - family: Montserrat-medium
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
    - family: HumaneIcons
      fonts:
        - asset: assets/icons/HumaneIcons.ttf

  # uses-material-design: true


  assets:
    - assets/GoStorages.flr
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/signin.svg
    - assets/icons/signup.svg
    - assets/icons/storage.svg
    - assets/icons/detailTop.svg
    - assets/icons/detailTopOpacity.svg
    - assets/icons/detailBottom.svg
    - assets/icons/promobg.svg
    - assets/icons/intro1.svg
    - assets/icons/intro2.svg
    - assets/icons/intro3.svg
    - assets/images/default.jpg
    - assets/images/logo.svg

