/// Flutter icons HumaneIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HumaneIcon
///      fonts:
///       - asset: fonts/HumaneIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HumaneIcon {
  HumaneIcon._();

  static const _kFontFam = 'HumaneIcon';
  static const String? _kFontPkg = null;

  static const IconData padlock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mother = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
