// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNEBTBJpJJobuq-gmoecDFs_ieF4DCreQ',
    appId: '1:880168898433:web:9e70a67fc8d6e0b7c8a280',
    messagingSenderId: '880168898433',
    projectId: 'humane-help',
    authDomain: 'humane-help.firebaseapp.com',
    databaseURL: 'https://humane-help-default-rtdb.firebaseio.com',
    storageBucket: 'humane-help.appspot.com',
    measurementId: 'G-VD41VG27GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqMb2RG3MXAvoyt8FCaUgpoe1_zCB-_k',
    appId: '1:880168898433:android:13a6e3af4957eb54c8a280',
    messagingSenderId: '880168898433',
    projectId: 'humane-help',
    databaseURL: 'https://humane-help-default-rtdb.firebaseio.com',
    storageBucket: 'humane-help.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58eOeGs4B7AKOgd84bMTsfLDYtKlCJ1I',
    appId: '1:880168898433:ios:446e5fd581a33715c8a280',
    messagingSenderId: '880168898433',
    projectId: 'humane-help',
    databaseURL: 'https://humane-help-default-rtdb.firebaseio.com',
    storageBucket: 'humane-help.appspot.com',
    iosClientId: '880168898433-saa6i6s4efhlb8tgudal3g0so383d709.apps.googleusercontent.com',
    iosBundleId: 'help.humane',
  );
}
